name: Build, Test & Trigger Deploy

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    # define node version
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # setting up node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # install
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm i
          npm ci

      # build
      - name: Build
        run: |
          npm run build

      # install playwright
      - name: Install Playwright with Chrome
        run: |
          npx playwright install --with-deps

      # run e2e
      - name: PlayWright Test
        run: |
          npx playwright test

      # Upload artifact of current build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-weather-app
          path: ./build

  deploy:
    # only deploy when PR has been merged to main branch & build job was successfully finished
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # first checkout to main
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: react-weather-app
          path: ./build

      # Deploy recent build and push it to branch 'gh-pages'
      # this will trigger the action 'pages build & deployment' to host the recent build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages